// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvGTKxgT2jBZ-Af9i4t6exlMhJGSKbKk',
    appId: '1:603546359307:web:f64a5b8392336b1df6590e',
    messagingSenderId: '603546359307',
    projectId: 'staff-sync-51245',
    authDomain: 'staff-sync-51245.firebaseapp.com',
    storageBucket: 'staff-sync-51245.firebasestorage.app',
    measurementId: 'G-3GH30HLJQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrOIypbIl0aP_OHz-aIkQ6vDd--N0I1No',
    appId: '1:603546359307:android:18a9d9d67f2b42a0f6590e',
    messagingSenderId: '603546359307',
    projectId: 'staff-sync-51245',
    storageBucket: 'staff-sync-51245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOwtWz6M7fYcwIO9C6w3rq1OuWqe0i2o',
    appId: '1:603546359307:ios:85fa38c3eb83d356f6590e',
    messagingSenderId: '603546359307',
    projectId: 'staff-sync-51245',
    storageBucket: 'staff-sync-51245.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOwtWz6M7fYcwIO9C6w3rq1OuWqe0i2o',
    appId: '1:603546359307:ios:85fa38c3eb83d356f6590e',
    messagingSenderId: '603546359307',
    projectId: 'staff-sync-51245',
    storageBucket: 'staff-sync-51245.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHvGTKxgT2jBZ-Af9i4t6exlMhJGSKbKk',
    appId: '1:603546359307:web:3480d7dfbde6ddbcf6590e',
    messagingSenderId: '603546359307',
    projectId: 'staff-sync-51245',
    authDomain: 'staff-sync-51245.firebaseapp.com',
    storageBucket: 'staff-sync-51245.firebasestorage.app',
    measurementId: 'G-VLQT380XJ1',
  );
}
