class DummyData {
  // Attendance Records
  static List<Map<String, dynamic>> attendanceHistory = [
    {
      'date': 'Dec 22, 2025',
      'checkIn': '09:00 AM',
      'checkOut': '06:00 PM',
      'duration': '9 hours',
      'location': 'Main Office, Gulberg',
      'status': 'present',
    },
    {
      'date': 'Dec 21, 2025',
      'checkIn': '09:05 AM',
      'checkOut': '06:15 PM',
      'duration': '9 hours 10 min',
      'location': 'Main Office, Gulberg',
      'status': 'present',
    },
    {
      'date': 'Dec 20, 2025',
      'checkIn': '08:55 AM',
      'checkOut': '06:05 PM',
      'duration': '9 hours 10 min',
      'location': 'Main Office, Gulberg',
      'status': 'present',
    },
    {
      'date': 'Dec 19, 2025',
      'checkIn': '09:10 AM',
      'checkOut': '06:20 PM',
      'duration': '9 hours 10 min',
      'location': 'Main Office, Gulberg',
      'status': 'present',
    },
    {
      'date': 'Dec 18, 2025',
      'checkIn': '-',
      'checkOut': '-',
      'duration': '-',
      'location': '-',
      'status': 'absent',
    },
  ];

  // Shifts
  static List<Map<String, dynamic>> shifts = [
    {
      'id': 1,
      'date': 'Dec 23, 2025',
      'title': 'Morning Shift',
      'type': 'morning',
      'startTime': '09:00 AM',
      'endTime': '05:00 PM',
      'location': 'Main Office, Gulberg',
      'role': 'Developer',
      'department': 'IT',
    },
    {
      'id': 2,
      'date': 'Dec 24, 2025',
      'title': 'Morning Shift',
      'type': 'morning',
      'startTime': '09:00 AM',
      'endTime': '05:00 PM',
      'location': 'Main Office, Gulberg',
      'role': 'Developer',
      'department': 'IT',
    },
    {
      'id': 3,
      'date': 'Dec 25, 2025',
      'title': 'Evening Shift',
      'type': 'evening',
      'startTime': '02:00 PM',
      'endTime': '10:00 PM',
      'location': 'Branch Office, DHA',
      'role': 'Support',
      'department': 'IT',
    },
    {
      'id': 4,
      'date': 'Dec 26, 2025',
      'title': 'Morning Shift',
      'type': 'morning',
      'startTime': '09:00 AM',
      'endTime': '05:00 PM',
      'location': 'Main Office, Gulberg',
      'role': 'Developer',
      'department': 'IT',
    },
    {
      'id': 5,
      'date': 'Dec 27, 2025',
      'title': 'Night Shift',
      'type': 'night',
      'startTime': '10:00 PM',
      'endTime': '06:00 AM',
      'location': 'Data Center, Johar Town',
      'role': 'Monitoring',
      'department': 'Operations',
    },
  ];

  // Leave Requests
  static List<Map<String, dynamic>> leaveRequests = [
    {
      'id': 1,
      'leaveType': 'Casual Leave',
      'fromDate': 'Dec 25, 2025',
      'toDate': 'Dec 27, 2025',
      'days': 3,
      'reason': 'Family event',
      'status': 'pending',
      'appliedDate': 'Dec 20, 2025',
    },
    {
      'id': 2,
      'leaveType': 'Sick Leave',
      'fromDate': 'Dec 15, 2025',
      'toDate': 'Dec 16, 2025',
      'days': 2,
      'reason': 'Medical checkup',
      'status': 'approved',
      'appliedDate': 'Dec 14, 2025',
    },
    {
      'id': 3,
      'leaveType': 'Annual Leave',
      'fromDate': 'Dec 10, 2025',
      'toDate': 'Dec 12, 2025',
      'days': 3,
      'reason': 'Personal work',
      'status': 'approved',
      'appliedDate': 'Dec 5, 2025',
    },
  ];

  // Tasks
  static List<Map<String, dynamic>> tasks = [
    {
      'id': 1,
      'title': 'Fix Login Bug',
      'description': 'The login button is not working properly on iOS devices',
      'priority': 'high',
      'status': 'pending',
      'dueDate': 'Dec 24, 2025',
      'dueTime': '05:00 PM',
      'assignedBy': 'Manager',
      'location': 'Main Office',
    },
    {
      'id': 2,
      'title': 'Update Database Schema',
      'description': 'Add new fields for employee attendance tracking',
      'priority': 'medium',
      'status': 'in-progress',
      'dueDate': 'Dec 25, 2025',
      'dueTime': '06:00 PM',
      'assignedBy': 'Tech Lead',
      'location': 'Remote',
    },
    {
      'id': 3,
      'title': 'Review Code Changes',
      'description': 'Review pull requests for the new feature branch',
      'priority': 'low',
      'status': 'pending',
      'dueDate': 'Dec 26, 2025',
      'dueTime': '03:00 PM',
      'assignedBy': 'Senior Dev',
      'location': 'Main Office',
    },
    {
      'id': 4,
      'title': 'Create User Documentation',
      'description': 'Write user manual for new attendance system',
      'priority': 'medium',
      'status': 'completed',
      'dueDate': 'Dec 20, 2025',
      'dueTime': '05:00 PM',
      'assignedBy': 'Project Manager',
      'location': 'Main Office',
    },
    {
      'id': 5,
      'title': 'Deploy to Production',
      'description': 'Deploy version 2.0 to production server',
      'priority': 'high',
      'status': 'completed',
      'dueDate': 'Dec 18, 2025',
      'dueTime': '11:00 PM',
      'assignedBy': 'DevOps Lead',
      'location': 'Data Center',
    },
  ];

  // Stats
  static Map<String, dynamic> stats = {
    'attendancePercentage': 95,
    'totalPresent': 22,
    'totalAbsent': 2,
    'totalShifts': 5,
    'totalLeaves': 3,
    'totalTasks': 8,
    'pendingTasks': 5,
    'completedTasks': 3,
    'casualLeaveBalance': 5,
    'sickLeaveBalance': 3,
    'annualLeaveBalance': 12,
  };
}
